name: Deploy Angular to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Build Angular project
        run: npm run build --prod
        working-directory: .

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/comments-ui:latest -f Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/comments-ui:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Comments-UI"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist/comments.ui

      - name: Trigger Azure Webhook
        run: curl -X POST -d '{}' ${{ secrets.AZURE_WEBHOOK_URL }}
